/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryId = string;
export type CategoryStatus = { 'delayed' : null } |
  { 'onTrack' : null } |
  { 'urgent' : null };
export interface CategoryView {
  'id' : CategoryId,
  'status' : CategoryStatus,
  'currentRound' : bigint,
  'name' : string,
  'matchesCompleted' : bigint,
  'avgDurationMinutes' : bigint,
  'numPlayers' : bigint,
  'matchesPending' : bigint,
}
export type ConflictType = { 'playerOnCourt' : null } |
  { 'notReady' : null } |
  { 'categoryClash' : null } |
  { 'backToBack' : null } |
  { 'timeRisk' : null } |
  { 'restNeeded' : null };
export interface CourtFlowConfigView {
  'startTime' : string,
  'status' : { 'panicMode' : null } |
    { 'completed' : null } |
    { 'setup' : null } |
    { 'inProgress' : null },
  'panicModeActive' : boolean,
  'endTime' : string,
  'venue' : string,
  'date' : string,
  'panicSuggestions' : Array<string>,
  'name' : string,
  'matchFormat' : string,
  'avgMatchDurationMinutes' : bigint,
  'minRestMinutes' : bigint,
  'courts' : Array<string>,
}
export interface CourtFlowCourtView {
  'courtId' : CourtId,
  'currentMatch' : [] | [MatchView],
  'isAvailable' : boolean,
  'recommendedNext' : [] | [QueueEntry],
  'courtName' : string,
}
export interface CourtFlowData {
  'matchQueue' : Array<QueueEntry>,
  'stats' : CourtFlowStats,
  'config' : CourtFlowConfigView,
  'courts' : Array<CourtFlowCourtView>,
}
export interface CourtFlowStats {
  'isRunningLate' : boolean,
  'suggestions' : Array<string>,
  'estimatedFinishTime' : string,
  'matchesCompleted' : bigint,
  'currentTime' : string,
  'tournamentEndTime' : string,
  'courtTimeRemainingMinutes' : bigint,
  'courtUtilisationPct' : bigint,
  'matchesPending' : bigint,
}
export type CourtId = bigint;
export interface DrawRow {
  'categoryId' : CategoryId,
  'player2Name' : string,
  'player1Name' : string,
  'round' : string,
  'estimatedMinutes' : bigint,
}
export interface ImportError { 'rowIndex' : bigint, 'reason' : string }
export interface ImportResult {
  'errors' : Array<ImportError>,
  'successCount' : bigint,
  'skippedCount' : bigint,
}
export type MatchId = bigint;
export type MatchStatus = { 'bye' : null } |
  { 'delayed' : null } |
  { 'completed' : null } |
  { 'notReady' : null } |
  { 'onCourt' : null } |
  { 'ready' : null };
export interface MatchView {
  'id' : MatchId,
  'player1Id' : [] | [PlayerId],
  'player2Id' : [] | [PlayerId],
  'categoryId' : CategoryId,
  'startTime' : [] | [string],
  'status' : MatchStatus,
  'categoryName' : string,
  'courtId' : [] | [CourtId],
  'estimatedDurationMinutes' : bigint,
  'endTime' : [] | [string],
  'winnerId' : [] | [PlayerId],
  'player2Name' : string,
  'conflicts' : Array<ConflictType>,
  'roundName' : string,
  'winnerName' : [] | [string],
  'priorityScore' : bigint,
  'scoreReason' : string,
  'dependsOnMatchIds' : Array<MatchId>,
  'player1Name' : string,
  'round' : bigint,
  'courtName' : [] | [string],
}
export interface OrderOfPlayEntry {
  'categoryId' : CategoryId,
  'categoryName' : string,
  'crossCategoryClashCount' : bigint,
  'totalMatches' : bigint,
  'rank' : bigint,
  'playerCount' : bigint,
  'cumulativeMinutesIfThisOrder' : bigint,
  'avgMatchDuration' : bigint,
  'estimatedTotalMinutes' : bigint,
  'reason' : string,
}
export type PlayerId = string;
export type PlayerStatus = { 'completed' : null } |
  { 'resting' : null } |
  { 'playing' : null } |
  { 'waiting' : null };
export interface PlayerView {
  'id' : PlayerId,
  'categories' : Array<CategoryId>,
  'status' : PlayerStatus,
  'lastMatchEndTime' : [] | [string],
  'seedNumber' : [] | [bigint],
  'name' : string,
  'totalWaitingMinutes' : bigint,
  'currentMatchId' : [] | [MatchId],
  'restRequiredUntil' : [] | [string],
  'matchesPlayedToday' : bigint,
}
export interface QueueEntry { 'match' : MatchView, 'rank' : bigint }
export interface RestedEntry {
  'lastMatchEndTime' : string,
  'restMinutesRemaining' : bigint,
  'playerId' : PlayerId,
  'playerName' : string,
}
export type Result = { 'ok' : MatchView } |
  { 'err' : string };
export type Result_1 = { 'ok' : CourtFlowCourtView } |
  { 'err' : string };
export interface TournamentConfigView {
  'startTime' : string,
  'status' : TournamentStatus,
  'panicModeActive' : boolean,
  'endTime' : string,
  'venue' : string,
  'date' : string,
  'panicSuggestions' : Array<string>,
  'name' : string,
  'matchFormat' : string,
  'avgMatchDurationMinutes' : bigint,
  'minRestMinutes' : bigint,
  'courts' : Array<string>,
}
export interface TournamentStats {
  'isRunningLate' : boolean,
  'suggestions' : Array<string>,
  'estimatedFinishTime' : string,
  'matchesCompleted' : bigint,
  'currentTime' : string,
  'tournamentEndTime' : string,
  'courtTimeRemainingMinutes' : bigint,
  'courtUtilisationPct' : bigint,
  'matchesPending' : bigint,
}
export type TournamentStatus = { 'panicMode' : null } |
  { 'completed' : null } |
  { 'setup' : null } |
  { 'inProgress' : null };
export interface UpdateTournamentConfigArgs {
  'startTime' : string,
  'courtNames' : Array<string>,
  'endTime' : string,
  'venue' : string,
  'date' : string,
  'name' : string,
  'matchFormat' : string,
  'avgMatchDurationMinutes' : bigint,
  'minRestMinutes' : bigint,
}
export interface WaitingEntry {
  'playerId' : PlayerId,
  'playerName' : string,
  'waitingMinutes' : bigint,
}
export interface WaitingTimeSummary {
  'averageWaitMinutes' : bigint,
  'warnings' : Array<WaitingWarning>,
  'longestWaiting' : Array<WaitingEntry>,
  'recentlyPlayed' : Array<RestedEntry>,
}
export interface WaitingWarning {
  'playerId' : PlayerId,
  'message' : string,
  'playerName' : string,
  'warningType' : WaitingWarningType,
}
export type WaitingWarningType = { 'waitedTooLong' : null } |
  { 'multiCategoryRisk' : null } |
  { 'backToBackRisk' : null };
export interface _SERVICE {
  'activatePanicMode' : ActorMethod<[], TournamentConfigView>,
  'addPlayer' : ActorMethod<
    [string, Array<CategoryId>, [] | [bigint]],
    PlayerView
  >,
  'assignMatchToCourt' : ActorMethod<[MatchId, CourtId], Result>,
  'completeMatch' : ActorMethod<[MatchId, PlayerId], Result>,
  'deactivatePanicMode' : ActorMethod<[], TournamentConfigView>,
  'delayMatch' : ActorMethod<[MatchId], Result>,
  'freeCourtManually' : ActorMethod<[CourtId], Result_1>,
  'getCourtFlowData' : ActorMethod<[], CourtFlowData>,
  'getMatch' : ActorMethod<[MatchId], [] | [MatchView]>,
  'getMatchQueue' : ActorMethod<[], Array<QueueEntry>>,
  'getOrderOfPlaySuggestion' : ActorMethod<[], Array<OrderOfPlayEntry>>,
  'getPlayer' : ActorMethod<[PlayerId], [] | [PlayerView]>,
  'getTournamentConfig' : ActorMethod<[], TournamentConfigView>,
  'getTournamentStats' : ActorMethod<[], TournamentStats>,
  'getWaitingTimeSummary' : ActorMethod<[], WaitingTimeSummary>,
  'importDraw' : ActorMethod<[Array<DrawRow>], ImportResult>,
  'listCategories' : ActorMethod<[], Array<CategoryView>>,
  'listMatches' : ActorMethod<[], Array<MatchView>>,
  'listPlayers' : ActorMethod<[], Array<PlayerView>>,
  'overrideMatch' : ActorMethod<[MatchId, CourtId], Result>,
  'removePlayer' : ActorMethod<[PlayerId], boolean>,
  'resetMatch' : ActorMethod<[MatchId], Result>,
  'startMatch' : ActorMethod<[MatchId, CourtId], Result>,
  'updatePlayer' : ActorMethod<
    [PlayerId, string, Array<CategoryId>, [] | [bigint]],
    [] | [PlayerView]
  >,
  'updateTournamentConfig' : ActorMethod<
    [UpdateTournamentConfigArgs],
    TournamentConfigView
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];