/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TournamentStatus = IDL.Variant({
  'panicMode' : IDL.Null,
  'completed' : IDL.Null,
  'setup' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TournamentConfigView = IDL.Record({
  'startTime' : IDL.Text,
  'status' : TournamentStatus,
  'panicModeActive' : IDL.Bool,
  'endTime' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'panicSuggestions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'matchFormat' : IDL.Text,
  'avgMatchDurationMinutes' : IDL.Nat,
  'minRestMinutes' : IDL.Nat,
  'courts' : IDL.Vec(IDL.Text),
});
export const CategoryId = IDL.Text;
export const PlayerId = IDL.Text;
export const PlayerStatus = IDL.Variant({
  'completed' : IDL.Null,
  'resting' : IDL.Null,
  'playing' : IDL.Null,
  'waiting' : IDL.Null,
});
export const MatchId = IDL.Nat;
export const PlayerView = IDL.Record({
  'id' : PlayerId,
  'categories' : IDL.Vec(CategoryId),
  'status' : PlayerStatus,
  'lastMatchEndTime' : IDL.Opt(IDL.Text),
  'seedNumber' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'totalWaitingMinutes' : IDL.Nat,
  'currentMatchId' : IDL.Opt(MatchId),
  'restRequiredUntil' : IDL.Opt(IDL.Text),
  'matchesPlayedToday' : IDL.Nat,
});
export const CourtId = IDL.Nat;
export const MatchStatus = IDL.Variant({
  'bye' : IDL.Null,
  'delayed' : IDL.Null,
  'completed' : IDL.Null,
  'notReady' : IDL.Null,
  'onCourt' : IDL.Null,
  'ready' : IDL.Null,
});
export const ConflictType = IDL.Variant({
  'playerOnCourt' : IDL.Null,
  'notReady' : IDL.Null,
  'categoryClash' : IDL.Null,
  'backToBack' : IDL.Null,
  'timeRisk' : IDL.Null,
  'restNeeded' : IDL.Null,
});
export const MatchView = IDL.Record({
  'id' : MatchId,
  'player1Id' : IDL.Opt(PlayerId),
  'player2Id' : IDL.Opt(PlayerId),
  'categoryId' : CategoryId,
  'startTime' : IDL.Opt(IDL.Text),
  'status' : MatchStatus,
  'categoryName' : IDL.Text,
  'courtId' : IDL.Opt(CourtId),
  'estimatedDurationMinutes' : IDL.Nat,
  'endTime' : IDL.Opt(IDL.Text),
  'winnerId' : IDL.Opt(PlayerId),
  'player2Name' : IDL.Text,
  'conflicts' : IDL.Vec(ConflictType),
  'roundName' : IDL.Text,
  'winnerName' : IDL.Opt(IDL.Text),
  'priorityScore' : IDL.Nat,
  'scoreReason' : IDL.Text,
  'dependsOnMatchIds' : IDL.Vec(MatchId),
  'player1Name' : IDL.Text,
  'round' : IDL.Nat,
  'courtName' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : MatchView, 'err' : IDL.Text });
export const QueueEntry = IDL.Record({ 'match' : MatchView, 'rank' : IDL.Nat });
export const CourtFlowCourtView = IDL.Record({
  'courtId' : CourtId,
  'currentMatch' : IDL.Opt(MatchView),
  'isAvailable' : IDL.Bool,
  'recommendedNext' : IDL.Opt(QueueEntry),
  'courtName' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : CourtFlowCourtView,
  'err' : IDL.Text,
});
export const CourtFlowStats = IDL.Record({
  'isRunningLate' : IDL.Bool,
  'suggestions' : IDL.Vec(IDL.Text),
  'estimatedFinishTime' : IDL.Text,
  'matchesCompleted' : IDL.Nat,
  'currentTime' : IDL.Text,
  'tournamentEndTime' : IDL.Text,
  'courtTimeRemainingMinutes' : IDL.Nat,
  'courtUtilisationPct' : IDL.Nat,
  'matchesPending' : IDL.Nat,
});
export const CourtFlowConfigView = IDL.Record({
  'startTime' : IDL.Text,
  'status' : IDL.Variant({
    'panicMode' : IDL.Null,
    'completed' : IDL.Null,
    'setup' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'panicModeActive' : IDL.Bool,
  'endTime' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'panicSuggestions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'matchFormat' : IDL.Text,
  'avgMatchDurationMinutes' : IDL.Nat,
  'minRestMinutes' : IDL.Nat,
  'courts' : IDL.Vec(IDL.Text),
});
export const CourtFlowData = IDL.Record({
  'matchQueue' : IDL.Vec(QueueEntry),
  'stats' : CourtFlowStats,
  'config' : CourtFlowConfigView,
  'courts' : IDL.Vec(CourtFlowCourtView),
});
export const OrderOfPlayEntry = IDL.Record({
  'categoryId' : CategoryId,
  'categoryName' : IDL.Text,
  'crossCategoryClashCount' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'rank' : IDL.Nat,
  'playerCount' : IDL.Nat,
  'cumulativeMinutesIfThisOrder' : IDL.Nat,
  'avgMatchDuration' : IDL.Nat,
  'estimatedTotalMinutes' : IDL.Nat,
  'reason' : IDL.Text,
});
export const TournamentStats = IDL.Record({
  'isRunningLate' : IDL.Bool,
  'suggestions' : IDL.Vec(IDL.Text),
  'estimatedFinishTime' : IDL.Text,
  'matchesCompleted' : IDL.Nat,
  'currentTime' : IDL.Text,
  'tournamentEndTime' : IDL.Text,
  'courtTimeRemainingMinutes' : IDL.Nat,
  'courtUtilisationPct' : IDL.Nat,
  'matchesPending' : IDL.Nat,
});
export const WaitingWarningType = IDL.Variant({
  'waitedTooLong' : IDL.Null,
  'multiCategoryRisk' : IDL.Null,
  'backToBackRisk' : IDL.Null,
});
export const WaitingWarning = IDL.Record({
  'playerId' : PlayerId,
  'message' : IDL.Text,
  'playerName' : IDL.Text,
  'warningType' : WaitingWarningType,
});
export const WaitingEntry = IDL.Record({
  'playerId' : PlayerId,
  'playerName' : IDL.Text,
  'waitingMinutes' : IDL.Nat,
});
export const RestedEntry = IDL.Record({
  'lastMatchEndTime' : IDL.Text,
  'restMinutesRemaining' : IDL.Nat,
  'playerId' : PlayerId,
  'playerName' : IDL.Text,
});
export const WaitingTimeSummary = IDL.Record({
  'averageWaitMinutes' : IDL.Nat,
  'warnings' : IDL.Vec(WaitingWarning),
  'longestWaiting' : IDL.Vec(WaitingEntry),
  'recentlyPlayed' : IDL.Vec(RestedEntry),
});
export const DrawRow = IDL.Record({
  'categoryId' : CategoryId,
  'player2Name' : IDL.Text,
  'player1Name' : IDL.Text,
  'round' : IDL.Text,
  'estimatedMinutes' : IDL.Nat,
});
export const ImportError = IDL.Record({
  'rowIndex' : IDL.Nat,
  'reason' : IDL.Text,
});
export const ImportResult = IDL.Record({
  'errors' : IDL.Vec(ImportError),
  'successCount' : IDL.Nat,
  'skippedCount' : IDL.Nat,
});
export const CategoryStatus = IDL.Variant({
  'delayed' : IDL.Null,
  'onTrack' : IDL.Null,
  'urgent' : IDL.Null,
});
export const CategoryView = IDL.Record({
  'id' : CategoryId,
  'status' : CategoryStatus,
  'currentRound' : IDL.Nat,
  'name' : IDL.Text,
  'matchesCompleted' : IDL.Nat,
  'avgDurationMinutes' : IDL.Nat,
  'numPlayers' : IDL.Nat,
  'matchesPending' : IDL.Nat,
});
export const UpdateTournamentConfigArgs = IDL.Record({
  'startTime' : IDL.Text,
  'courtNames' : IDL.Vec(IDL.Text),
  'endTime' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'matchFormat' : IDL.Text,
  'avgMatchDurationMinutes' : IDL.Nat,
  'minRestMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'activatePanicMode' : IDL.Func([], [TournamentConfigView], []),
  'addPlayer' : IDL.Func(
      [IDL.Text, IDL.Vec(CategoryId), IDL.Opt(IDL.Nat)],
      [PlayerView],
      [],
    ),
  'assignMatchToCourt' : IDL.Func([MatchId, CourtId], [Result], []),
  'completeMatch' : IDL.Func([MatchId, PlayerId], [Result], []),
  'deactivatePanicMode' : IDL.Func([], [TournamentConfigView], []),
  'delayMatch' : IDL.Func([MatchId], [Result], []),
  'freeCourtManually' : IDL.Func([CourtId], [Result_1], []),
  'getCourtFlowData' : IDL.Func([], [CourtFlowData], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchView)], ['query']),
  'getMatchQueue' : IDL.Func([], [IDL.Vec(QueueEntry)], ['query']),
  'getOrderOfPlaySuggestion' : IDL.Func(
      [],
      [IDL.Vec(OrderOfPlayEntry)],
      ['query'],
    ),
  'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(PlayerView)], ['query']),
  'getTournamentConfig' : IDL.Func([], [TournamentConfigView], ['query']),
  'getTournamentStats' : IDL.Func([], [TournamentStats], ['query']),
  'getWaitingTimeSummary' : IDL.Func([], [WaitingTimeSummary], ['query']),
  'importDraw' : IDL.Func([IDL.Vec(DrawRow)], [ImportResult], []),
  'listCategories' : IDL.Func([], [IDL.Vec(CategoryView)], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
  'listPlayers' : IDL.Func([], [IDL.Vec(PlayerView)], ['query']),
  'overrideMatch' : IDL.Func([MatchId, CourtId], [Result], []),
  'removePlayer' : IDL.Func([PlayerId], [IDL.Bool], []),
  'resetMatch' : IDL.Func([MatchId], [Result], []),
  'startMatch' : IDL.Func([MatchId, CourtId], [Result], []),
  'updatePlayer' : IDL.Func(
      [PlayerId, IDL.Text, IDL.Vec(CategoryId), IDL.Opt(IDL.Nat)],
      [IDL.Opt(PlayerView)],
      [],
    ),
  'updateTournamentConfig' : IDL.Func(
      [UpdateTournamentConfigArgs],
      [TournamentConfigView],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TournamentStatus = IDL.Variant({
    'panicMode' : IDL.Null,
    'completed' : IDL.Null,
    'setup' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TournamentConfigView = IDL.Record({
    'startTime' : IDL.Text,
    'status' : TournamentStatus,
    'panicModeActive' : IDL.Bool,
    'endTime' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'panicSuggestions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'matchFormat' : IDL.Text,
    'avgMatchDurationMinutes' : IDL.Nat,
    'minRestMinutes' : IDL.Nat,
    'courts' : IDL.Vec(IDL.Text),
  });
  const CategoryId = IDL.Text;
  const PlayerId = IDL.Text;
  const PlayerStatus = IDL.Variant({
    'completed' : IDL.Null,
    'resting' : IDL.Null,
    'playing' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const MatchId = IDL.Nat;
  const PlayerView = IDL.Record({
    'id' : PlayerId,
    'categories' : IDL.Vec(CategoryId),
    'status' : PlayerStatus,
    'lastMatchEndTime' : IDL.Opt(IDL.Text),
    'seedNumber' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'totalWaitingMinutes' : IDL.Nat,
    'currentMatchId' : IDL.Opt(MatchId),
    'restRequiredUntil' : IDL.Opt(IDL.Text),
    'matchesPlayedToday' : IDL.Nat,
  });
  const CourtId = IDL.Nat;
  const MatchStatus = IDL.Variant({
    'bye' : IDL.Null,
    'delayed' : IDL.Null,
    'completed' : IDL.Null,
    'notReady' : IDL.Null,
    'onCourt' : IDL.Null,
    'ready' : IDL.Null,
  });
  const ConflictType = IDL.Variant({
    'playerOnCourt' : IDL.Null,
    'notReady' : IDL.Null,
    'categoryClash' : IDL.Null,
    'backToBack' : IDL.Null,
    'timeRisk' : IDL.Null,
    'restNeeded' : IDL.Null,
  });
  const MatchView = IDL.Record({
    'id' : MatchId,
    'player1Id' : IDL.Opt(PlayerId),
    'player2Id' : IDL.Opt(PlayerId),
    'categoryId' : CategoryId,
    'startTime' : IDL.Opt(IDL.Text),
    'status' : MatchStatus,
    'categoryName' : IDL.Text,
    'courtId' : IDL.Opt(CourtId),
    'estimatedDurationMinutes' : IDL.Nat,
    'endTime' : IDL.Opt(IDL.Text),
    'winnerId' : IDL.Opt(PlayerId),
    'player2Name' : IDL.Text,
    'conflicts' : IDL.Vec(ConflictType),
    'roundName' : IDL.Text,
    'winnerName' : IDL.Opt(IDL.Text),
    'priorityScore' : IDL.Nat,
    'scoreReason' : IDL.Text,
    'dependsOnMatchIds' : IDL.Vec(MatchId),
    'player1Name' : IDL.Text,
    'round' : IDL.Nat,
    'courtName' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : MatchView, 'err' : IDL.Text });
  const QueueEntry = IDL.Record({ 'match' : MatchView, 'rank' : IDL.Nat });
  const CourtFlowCourtView = IDL.Record({
    'courtId' : CourtId,
    'currentMatch' : IDL.Opt(MatchView),
    'isAvailable' : IDL.Bool,
    'recommendedNext' : IDL.Opt(QueueEntry),
    'courtName' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : CourtFlowCourtView, 'err' : IDL.Text });
  const CourtFlowStats = IDL.Record({
    'isRunningLate' : IDL.Bool,
    'suggestions' : IDL.Vec(IDL.Text),
    'estimatedFinishTime' : IDL.Text,
    'matchesCompleted' : IDL.Nat,
    'currentTime' : IDL.Text,
    'tournamentEndTime' : IDL.Text,
    'courtTimeRemainingMinutes' : IDL.Nat,
    'courtUtilisationPct' : IDL.Nat,
    'matchesPending' : IDL.Nat,
  });
  const CourtFlowConfigView = IDL.Record({
    'startTime' : IDL.Text,
    'status' : IDL.Variant({
      'panicMode' : IDL.Null,
      'completed' : IDL.Null,
      'setup' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'panicModeActive' : IDL.Bool,
    'endTime' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'panicSuggestions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'matchFormat' : IDL.Text,
    'avgMatchDurationMinutes' : IDL.Nat,
    'minRestMinutes' : IDL.Nat,
    'courts' : IDL.Vec(IDL.Text),
  });
  const CourtFlowData = IDL.Record({
    'matchQueue' : IDL.Vec(QueueEntry),
    'stats' : CourtFlowStats,
    'config' : CourtFlowConfigView,
    'courts' : IDL.Vec(CourtFlowCourtView),
  });
  const OrderOfPlayEntry = IDL.Record({
    'categoryId' : CategoryId,
    'categoryName' : IDL.Text,
    'crossCategoryClashCount' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'rank' : IDL.Nat,
    'playerCount' : IDL.Nat,
    'cumulativeMinutesIfThisOrder' : IDL.Nat,
    'avgMatchDuration' : IDL.Nat,
    'estimatedTotalMinutes' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const TournamentStats = IDL.Record({
    'isRunningLate' : IDL.Bool,
    'suggestions' : IDL.Vec(IDL.Text),
    'estimatedFinishTime' : IDL.Text,
    'matchesCompleted' : IDL.Nat,
    'currentTime' : IDL.Text,
    'tournamentEndTime' : IDL.Text,
    'courtTimeRemainingMinutes' : IDL.Nat,
    'courtUtilisationPct' : IDL.Nat,
    'matchesPending' : IDL.Nat,
  });
  const WaitingWarningType = IDL.Variant({
    'waitedTooLong' : IDL.Null,
    'multiCategoryRisk' : IDL.Null,
    'backToBackRisk' : IDL.Null,
  });
  const WaitingWarning = IDL.Record({
    'playerId' : PlayerId,
    'message' : IDL.Text,
    'playerName' : IDL.Text,
    'warningType' : WaitingWarningType,
  });
  const WaitingEntry = IDL.Record({
    'playerId' : PlayerId,
    'playerName' : IDL.Text,
    'waitingMinutes' : IDL.Nat,
  });
  const RestedEntry = IDL.Record({
    'lastMatchEndTime' : IDL.Text,
    'restMinutesRemaining' : IDL.Nat,
    'playerId' : PlayerId,
    'playerName' : IDL.Text,
  });
  const WaitingTimeSummary = IDL.Record({
    'averageWaitMinutes' : IDL.Nat,
    'warnings' : IDL.Vec(WaitingWarning),
    'longestWaiting' : IDL.Vec(WaitingEntry),
    'recentlyPlayed' : IDL.Vec(RestedEntry),
  });
  const DrawRow = IDL.Record({
    'categoryId' : CategoryId,
    'player2Name' : IDL.Text,
    'player1Name' : IDL.Text,
    'round' : IDL.Text,
    'estimatedMinutes' : IDL.Nat,
  });
  const ImportError = IDL.Record({ 'rowIndex' : IDL.Nat, 'reason' : IDL.Text });
  const ImportResult = IDL.Record({
    'errors' : IDL.Vec(ImportError),
    'successCount' : IDL.Nat,
    'skippedCount' : IDL.Nat,
  });
  const CategoryStatus = IDL.Variant({
    'delayed' : IDL.Null,
    'onTrack' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const CategoryView = IDL.Record({
    'id' : CategoryId,
    'status' : CategoryStatus,
    'currentRound' : IDL.Nat,
    'name' : IDL.Text,
    'matchesCompleted' : IDL.Nat,
    'avgDurationMinutes' : IDL.Nat,
    'numPlayers' : IDL.Nat,
    'matchesPending' : IDL.Nat,
  });
  const UpdateTournamentConfigArgs = IDL.Record({
    'startTime' : IDL.Text,
    'courtNames' : IDL.Vec(IDL.Text),
    'endTime' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'matchFormat' : IDL.Text,
    'avgMatchDurationMinutes' : IDL.Nat,
    'minRestMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    'activatePanicMode' : IDL.Func([], [TournamentConfigView], []),
    'addPlayer' : IDL.Func(
        [IDL.Text, IDL.Vec(CategoryId), IDL.Opt(IDL.Nat)],
        [PlayerView],
        [],
      ),
    'assignMatchToCourt' : IDL.Func([MatchId, CourtId], [Result], []),
    'completeMatch' : IDL.Func([MatchId, PlayerId], [Result], []),
    'deactivatePanicMode' : IDL.Func([], [TournamentConfigView], []),
    'delayMatch' : IDL.Func([MatchId], [Result], []),
    'freeCourtManually' : IDL.Func([CourtId], [Result_1], []),
    'getCourtFlowData' : IDL.Func([], [CourtFlowData], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchView)], ['query']),
    'getMatchQueue' : IDL.Func([], [IDL.Vec(QueueEntry)], ['query']),
    'getOrderOfPlaySuggestion' : IDL.Func(
        [],
        [IDL.Vec(OrderOfPlayEntry)],
        ['query'],
      ),
    'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(PlayerView)], ['query']),
    'getTournamentConfig' : IDL.Func([], [TournamentConfigView], ['query']),
    'getTournamentStats' : IDL.Func([], [TournamentStats], ['query']),
    'getWaitingTimeSummary' : IDL.Func([], [WaitingTimeSummary], ['query']),
    'importDraw' : IDL.Func([IDL.Vec(DrawRow)], [ImportResult], []),
    'listCategories' : IDL.Func([], [IDL.Vec(CategoryView)], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
    'listPlayers' : IDL.Func([], [IDL.Vec(PlayerView)], ['query']),
    'overrideMatch' : IDL.Func([MatchId, CourtId], [Result], []),
    'removePlayer' : IDL.Func([PlayerId], [IDL.Bool], []),
    'resetMatch' : IDL.Func([MatchId], [Result], []),
    'startMatch' : IDL.Func([MatchId, CourtId], [Result], []),
    'updatePlayer' : IDL.Func(
        [PlayerId, IDL.Text, IDL.Vec(CategoryId), IDL.Opt(IDL.Nat)],
        [IDL.Opt(PlayerView)],
        [],
      ),
    'updateTournamentConfig' : IDL.Func(
        [UpdateTournamentConfigArgs],
        [TournamentConfigView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };