/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TournamentConfigView {
    startTime: string;
    status: TournamentStatus;
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
}
export type CourtId = bigint;
export interface CourtFlowConfigView {
    startTime: string;
    status: Variant_panicMode_completed_setup_inProgress;
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
}
export interface ImportResult {
    errors: Array<ImportError>;
    successCount: bigint;
    skippedCount: bigint;
}
export interface MatchView {
    id: MatchId;
    player1Id?: PlayerId;
    player2Id?: PlayerId;
    categoryId: CategoryId;
    startTime?: string;
    status: MatchStatus;
    categoryName: string;
    courtId?: CourtId;
    estimatedDurationMinutes: bigint;
    endTime?: string;
    winnerId?: PlayerId;
    player2Name: string;
    conflicts: Array<ConflictType>;
    roundName: string;
    winnerName?: string;
    priorityScore: bigint;
    scoreReason: string;
    dependsOnMatchIds: Array<MatchId>;
    player1Name: string;
    round: bigint;
    courtName?: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: CourtFlowCourtView;
} | {
    __kind__: "err";
    err: string;
};
export type MatchId = bigint;
export interface RestedEntry {
    lastMatchEndTime: string;
    restMinutesRemaining: bigint;
    playerId: PlayerId;
    playerName: string;
}
export interface UpdateTournamentConfigArgs {
    startTime: string;
    courtNames: Array<string>;
    endTime: string;
    venue: string;
    date: string;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
}
export type PlayerId = string;
export interface CourtFlowStats {
    isRunningLate: boolean;
    suggestions: Array<string>;
    estimatedFinishTime: string;
    matchesCompleted: bigint;
    currentTime: string;
    tournamentEndTime: string;
    courtTimeRemainingMinutes: bigint;
    courtUtilisationPct: bigint;
    matchesPending: bigint;
}
export interface DrawRow {
    categoryId: CategoryId;
    player2Name: string;
    player1Name: string;
    round: string;
    estimatedMinutes: bigint;
}
export interface PlayerView {
    id: PlayerId;
    categories: Array<CategoryId>;
    status: PlayerStatus;
    lastMatchEndTime?: string;
    seedNumber?: bigint;
    name: string;
    totalWaitingMinutes: bigint;
    currentMatchId?: MatchId;
    restRequiredUntil?: string;
    matchesPlayedToday: bigint;
}
export interface WaitingWarning {
    playerId: PlayerId;
    message: string;
    playerName: string;
    warningType: WaitingWarningType;
}
export interface WaitingTimeSummary {
    averageWaitMinutes: bigint;
    warnings: Array<WaitingWarning>;
    longestWaiting: Array<WaitingEntry>;
    recentlyPlayed: Array<RestedEntry>;
}
export interface CourtFlowData {
    matchQueue: Array<QueueEntry>;
    stats: CourtFlowStats;
    config: CourtFlowConfigView;
    courts: Array<CourtFlowCourtView>;
}
export interface OrderOfPlayEntry {
    categoryId: CategoryId;
    categoryName: string;
    crossCategoryClashCount: bigint;
    totalMatches: bigint;
    rank: bigint;
    playerCount: bigint;
    cumulativeMinutesIfThisOrder: bigint;
    avgMatchDuration: bigint;
    estimatedTotalMinutes: bigint;
    reason: string;
}
export interface ImportError {
    rowIndex: bigint;
    reason: string;
}
export interface TournamentStats {
    isRunningLate: boolean;
    suggestions: Array<string>;
    estimatedFinishTime: string;
    matchesCompleted: bigint;
    currentTime: string;
    tournamentEndTime: string;
    courtTimeRemainingMinutes: bigint;
    courtUtilisationPct: bigint;
    matchesPending: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: MatchView;
} | {
    __kind__: "err";
    err: string;
};
export interface CourtFlowCourtView {
    courtId: CourtId;
    currentMatch?: MatchView;
    isAvailable: boolean;
    recommendedNext?: QueueEntry;
    courtName: string;
}
export interface QueueEntry {
    match: MatchView;
    rank: bigint;
}
export type CategoryId = string;
export interface WaitingEntry {
    playerId: PlayerId;
    playerName: string;
    waitingMinutes: bigint;
}
export interface CategoryView {
    id: CategoryId;
    status: CategoryStatus;
    currentRound: bigint;
    name: string;
    matchesCompleted: bigint;
    avgDurationMinutes: bigint;
    numPlayers: bigint;
    matchesPending: bigint;
}
export enum CategoryStatus {
    delayed = "delayed",
    onTrack = "onTrack",
    urgent = "urgent"
}
export enum ConflictType {
    playerOnCourt = "playerOnCourt",
    notReady = "notReady",
    categoryClash = "categoryClash",
    backToBack = "backToBack",
    timeRisk = "timeRisk",
    restNeeded = "restNeeded"
}
export enum MatchStatus {
    bye = "bye",
    delayed = "delayed",
    completed = "completed",
    notReady = "notReady",
    onCourt = "onCourt",
    ready = "ready"
}
export enum PlayerStatus {
    completed = "completed",
    resting = "resting",
    playing = "playing",
    waiting = "waiting"
}
export enum Variant_panicMode_completed_setup_inProgress {
    panicMode = "panicMode",
    completed = "completed",
    setup = "setup",
    inProgress = "inProgress"
}
export enum WaitingWarningType {
    waitedTooLong = "waitedTooLong",
    multiCategoryRisk = "multiCategoryRisk",
    backToBackRisk = "backToBackRisk"
}
export interface backendInterface {
    activatePanicMode(): Promise<TournamentConfigView>;
    addPlayer(name: string, categories: Array<CategoryId>, seedNumber: bigint | null): Promise<PlayerView>;
    assignMatchToCourt(matchId: MatchId, courtId: CourtId): Promise<Result>;
    completeMatch(matchId: MatchId, winnerId: PlayerId): Promise<Result>;
    deactivatePanicMode(): Promise<TournamentConfigView>;
    delayMatch(matchId: MatchId): Promise<Result>;
    freeCourtManually(courtId: CourtId): Promise<Result_1>;
    getCourtFlowData(): Promise<CourtFlowData>;
    getMatch(matchId: MatchId): Promise<MatchView | null>;
    getMatchQueue(): Promise<Array<QueueEntry>>;
    getOrderOfPlaySuggestion(): Promise<Array<OrderOfPlayEntry>>;
    getPlayer(playerId: PlayerId): Promise<PlayerView | null>;
    getTournamentConfig(): Promise<TournamentConfigView>;
    getTournamentStats(): Promise<TournamentStats>;
    getWaitingTimeSummary(): Promise<WaitingTimeSummary>;
    importDraw(rows: Array<DrawRow>): Promise<ImportResult>;
    listCategories(): Promise<Array<CategoryView>>;
    listMatches(): Promise<Array<MatchView>>;
    listPlayers(): Promise<Array<PlayerView>>;
    overrideMatch(matchId: MatchId, courtId: CourtId): Promise<Result>;
    removePlayer(playerId: PlayerId): Promise<boolean>;
    resetMatch(matchId: MatchId): Promise<Result>;
    startMatch(matchId: MatchId, courtId: CourtId): Promise<Result>;
    updatePlayer(playerId: PlayerId, name: string, categories: Array<CategoryId>, seedNumber: bigint | null): Promise<PlayerView | null>;
    updateTournamentConfig(args: UpdateTournamentConfigArgs): Promise<TournamentConfigView>;
}
import type { CategoryId as _CategoryId, CategoryStatus as _CategoryStatus, CategoryView as _CategoryView, ConflictType as _ConflictType, CourtFlowConfigView as _CourtFlowConfigView, CourtFlowCourtView as _CourtFlowCourtView, CourtFlowData as _CourtFlowData, CourtFlowStats as _CourtFlowStats, CourtId as _CourtId, MatchId as _MatchId, MatchStatus as _MatchStatus, MatchView as _MatchView, PlayerId as _PlayerId, PlayerStatus as _PlayerStatus, PlayerView as _PlayerView, QueueEntry as _QueueEntry, RestedEntry as _RestedEntry, Result as _Result, Result_1 as _Result_1, TournamentConfigView as _TournamentConfigView, TournamentStatus as _TournamentStatus, WaitingEntry as _WaitingEntry, WaitingTimeSummary as _WaitingTimeSummary, WaitingWarning as _WaitingWarning, WaitingWarningType as _WaitingWarningType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activatePanicMode(): Promise<TournamentConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePanicMode();
                return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePanicMode();
            return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPlayer(arg0: string, arg1: Array<CategoryId>, arg2: bigint | null): Promise<PlayerView> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PlayerView_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PlayerView_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignMatchToCourt(arg0: MatchId, arg1: CourtId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.assignMatchToCourt(arg0, arg1);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignMatchToCourt(arg0, arg1);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeMatch(arg0: MatchId, arg1: PlayerId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMatch(arg0, arg1);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMatch(arg0, arg1);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivatePanicMode(): Promise<TournamentConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivatePanicMode();
                return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivatePanicMode();
            return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async delayMatch(arg0: MatchId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.delayMatch(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delayMatch(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async freeCourtManually(arg0: CourtId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.freeCourtManually(arg0);
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.freeCourtManually(arg0);
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourtFlowData(): Promise<CourtFlowData> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourtFlowData();
                return from_candid_CourtFlowData_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourtFlowData();
            return from_candid_CourtFlowData_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: MatchId): Promise<MatchView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchQueue(): Promise<Array<QueueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchQueue();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchQueue();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderOfPlaySuggestion(): Promise<Array<OrderOfPlayEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderOfPlaySuggestion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderOfPlaySuggestion();
            return result;
        }
    }
    async getPlayer(arg0: PlayerId): Promise<PlayerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentConfig(): Promise<TournamentConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentConfig();
                return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentConfig();
            return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentStats(): Promise<TournamentStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentStats();
            return result;
        }
    }
    async getWaitingTimeSummary(): Promise<WaitingTimeSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitingTimeSummary();
                return from_candid_WaitingTimeSummary_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitingTimeSummary();
            return from_candid_WaitingTimeSummary_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async importDraw(arg0: Array<DrawRow>): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importDraw(arg0);
            return result;
        }
    }
    async listCategories(): Promise<Array<CategoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMatches(): Promise<Array<MatchView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPlayers(): Promise<Array<PlayerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayers();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayers();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async overrideMatch(arg0: MatchId, arg1: CourtId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.overrideMatch(arg0, arg1);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overrideMatch(arg0, arg1);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async removePlayer(arg0: PlayerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayer(arg0);
            return result;
        }
    }
    async resetMatch(arg0: MatchId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMatch(arg0);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMatch(arg0);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async startMatch(arg0: MatchId, arg1: CourtId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.startMatch(arg0, arg1);
                return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startMatch(arg0, arg1);
            return from_candid_Result_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlayer(arg0: PlayerId, arg1: string, arg2: Array<CategoryId>, arg3: bigint | null): Promise<PlayerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTournamentConfig(arg0: UpdateTournamentConfigArgs): Promise<TournamentConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentConfig(arg0);
                return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentConfig(arg0);
            return from_candid_TournamentConfigView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CategoryStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryStatus): CategoryStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryView_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryView): CategoryView {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ConflictType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConflictType): ConflictType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CourtFlowConfigView_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourtFlowConfigView): CourtFlowConfigView {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_CourtFlowCourtView_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourtFlowCourtView): CourtFlowCourtView {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CourtFlowData_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourtFlowData): CourtFlowData {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MatchView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchView): MatchView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStatus): PlayerStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerView): PlayerView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_QueueEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueEntry): QueueEntry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentConfigView_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentConfigView): TournamentConfigView {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_WaitingTimeSummary_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitingTimeSummary): WaitingTimeSummary {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_WaitingWarningType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitingWarningType): WaitingWarningType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_WaitingWarning_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaitingWarning): WaitingWarning {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchId]): MatchId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerId]): PlayerId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourtId]): CourtId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchView]): MatchView | null {
    return value.length === 0 ? null : from_candid_MatchView_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QueueEntry]): QueueEntry | null {
    return value.length === 0 ? null : from_candid_QueueEntry_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerView]): PlayerView | null {
    return value.length === 0 ? null : from_candid_PlayerView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    player1Id: [] | [_PlayerId];
    player2Id: [] | [_PlayerId];
    categoryId: _CategoryId;
    startTime: [] | [string];
    status: _MatchStatus;
    categoryName: string;
    courtId: [] | [_CourtId];
    estimatedDurationMinutes: bigint;
    endTime: [] | [string];
    winnerId: [] | [_PlayerId];
    player2Name: string;
    conflicts: Array<_ConflictType>;
    roundName: string;
    winnerName: [] | [string];
    priorityScore: bigint;
    scoreReason: string;
    dependsOnMatchIds: Array<_MatchId>;
    player1Name: string;
    round: bigint;
    courtName: [] | [string];
}): {
    id: MatchId;
    player1Id?: PlayerId;
    player2Id?: PlayerId;
    categoryId: CategoryId;
    startTime?: string;
    status: MatchStatus;
    categoryName: string;
    courtId?: CourtId;
    estimatedDurationMinutes: bigint;
    endTime?: string;
    winnerId?: PlayerId;
    player2Name: string;
    conflicts: Array<ConflictType>;
    roundName: string;
    winnerName?: string;
    priorityScore: bigint;
    scoreReason: string;
    dependsOnMatchIds: Array<MatchId>;
    player1Name: string;
    round: bigint;
    courtName?: string;
} {
    return {
        id: value.id,
        player1Id: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.player1Id)),
        player2Id: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.player2Id)),
        categoryId: value.categoryId,
        startTime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.startTime)),
        status: from_candid_MatchStatus_n18(_uploadFile, _downloadFile, value.status),
        categoryName: value.categoryName,
        courtId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.courtId)),
        estimatedDurationMinutes: value.estimatedDurationMinutes,
        endTime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.endTime)),
        winnerId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.winnerId)),
        player2Name: value.player2Name,
        conflicts: from_candid_vec_n21(_uploadFile, _downloadFile, value.conflicts),
        roundName: value.roundName,
        winnerName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.winnerName)),
        priorityScore: value.priorityScore,
        scoreReason: value.scoreReason,
        dependsOnMatchIds: value.dependsOnMatchIds,
        player1Name: value.player1Name,
        round: value.round,
        courtName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.courtName))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    status: _TournamentStatus;
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
}): {
    startTime: string;
    status: TournamentStatus;
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
} {
    return {
        startTime: value.startTime,
        status: from_candid_TournamentStatus_n3(_uploadFile, _downloadFile, value.status),
        panicModeActive: value.panicModeActive,
        endTime: value.endTime,
        venue: value.venue,
        date: value.date,
        panicSuggestions: value.panicSuggestions,
        name: value.name,
        matchFormat: value.matchFormat,
        avgMatchDurationMinutes: value.avgMatchDurationMinutes,
        minRestMinutes: value.minRestMinutes,
        courts: value.courts
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courtId: _CourtId;
    currentMatch: [] | [_MatchView];
    isAvailable: boolean;
    recommendedNext: [] | [_QueueEntry];
    courtName: string;
}): {
    courtId: CourtId;
    currentMatch?: MatchView;
    isAvailable: boolean;
    recommendedNext?: QueueEntry;
    courtName: string;
} {
    return {
        courtId: value.courtId,
        currentMatch: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.currentMatch)),
        isAvailable: value.isAvailable,
        recommendedNext: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.recommendedNext)),
        courtName: value.courtName
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    match: _MatchView;
    rank: bigint;
}): {
    match: MatchView;
    rank: bigint;
} {
    return {
        match: from_candid_MatchView_n15(_uploadFile, _downloadFile, value.match),
        rank: value.rank
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchQueue: Array<_QueueEntry>;
    stats: _CourtFlowStats;
    config: _CourtFlowConfigView;
    courts: Array<_CourtFlowCourtView>;
}): {
    matchQueue: Array<QueueEntry>;
    stats: CourtFlowStats;
    config: CourtFlowConfigView;
    courts: Array<CourtFlowCourtView>;
} {
    return {
        matchQueue: from_candid_vec_n34(_uploadFile, _downloadFile, value.matchQueue),
        stats: value.stats,
        config: from_candid_CourtFlowConfigView_n35(_uploadFile, _downloadFile, value.config),
        courts: from_candid_vec_n37(_uploadFile, _downloadFile, value.courts)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    status: {
        panicMode: null;
    } | {
        completed: null;
    } | {
        setup: null;
    } | {
        inProgress: null;
    };
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
}): {
    startTime: string;
    status: Variant_panicMode_completed_setup_inProgress;
    panicModeActive: boolean;
    endTime: string;
    venue: string;
    date: string;
    panicSuggestions: Array<string>;
    name: string;
    matchFormat: string;
    avgMatchDurationMinutes: bigint;
    minRestMinutes: bigint;
    courts: Array<string>;
} {
    return {
        startTime: value.startTime,
        status: from_candid_variant_n4(_uploadFile, _downloadFile, value.status),
        panicModeActive: value.panicModeActive,
        endTime: value.endTime,
        venue: value.venue,
        date: value.date,
        panicSuggestions: value.panicSuggestions,
        name: value.name,
        matchFormat: value.matchFormat,
        avgMatchDurationMinutes: value.avgMatchDurationMinutes,
        minRestMinutes: value.minRestMinutes,
        courts: value.courts
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageWaitMinutes: bigint;
    warnings: Array<_WaitingWarning>;
    longestWaiting: Array<_WaitingEntry>;
    recentlyPlayed: Array<_RestedEntry>;
}): {
    averageWaitMinutes: bigint;
    warnings: Array<WaitingWarning>;
    longestWaiting: Array<WaitingEntry>;
    recentlyPlayed: Array<RestedEntry>;
} {
    return {
        averageWaitMinutes: value.averageWaitMinutes,
        warnings: from_candid_vec_n41(_uploadFile, _downloadFile, value.warnings),
        longestWaiting: value.longestWaiting,
        recentlyPlayed: value.recentlyPlayed
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerId: _PlayerId;
    message: string;
    playerName: string;
    warningType: _WaitingWarningType;
}): {
    playerId: PlayerId;
    message: string;
    playerName: string;
    warningType: WaitingWarningType;
} {
    return {
        playerId: value.playerId,
        message: value.message,
        playerName: value.playerName,
        warningType: from_candid_WaitingWarningType_n44(_uploadFile, _downloadFile, value.warningType)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CategoryId;
    status: _CategoryStatus;
    currentRound: bigint;
    name: string;
    matchesCompleted: bigint;
    avgDurationMinutes: bigint;
    numPlayers: bigint;
    matchesPending: bigint;
}): {
    id: CategoryId;
    status: CategoryStatus;
    currentRound: bigint;
    name: string;
    matchesCompleted: bigint;
    avgDurationMinutes: bigint;
    numPlayers: bigint;
    matchesPending: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CategoryStatus_n49(_uploadFile, _downloadFile, value.status),
        currentRound: value.currentRound,
        name: value.name,
        matchesCompleted: value.matchesCompleted,
        avgDurationMinutes: value.avgDurationMinutes,
        numPlayers: value.numPlayers,
        matchesPending: value.matchesPending
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    categories: Array<_CategoryId>;
    status: _PlayerStatus;
    lastMatchEndTime: [] | [string];
    seedNumber: [] | [bigint];
    name: string;
    totalWaitingMinutes: bigint;
    currentMatchId: [] | [_MatchId];
    restRequiredUntil: [] | [string];
    matchesPlayedToday: bigint;
}): {
    id: PlayerId;
    categories: Array<CategoryId>;
    status: PlayerStatus;
    lastMatchEndTime?: string;
    seedNumber?: bigint;
    name: string;
    totalWaitingMinutes: bigint;
    currentMatchId?: MatchId;
    restRequiredUntil?: string;
    matchesPlayedToday: bigint;
} {
    return {
        id: value.id,
        categories: value.categories,
        status: from_candid_PlayerStatus_n8(_uploadFile, _downloadFile, value.status),
        lastMatchEndTime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastMatchEndTime)),
        seedNumber: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.seedNumber)),
        name: value.name,
        totalWaitingMinutes: value.totalWaitingMinutes,
        currentMatchId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.currentMatchId)),
        restRequiredUntil: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.restRequiredUntil)),
        matchesPlayedToday: value.matchesPlayedToday
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MatchView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MatchView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MatchView_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bye: null;
} | {
    delayed: null;
} | {
    completed: null;
} | {
    notReady: null;
} | {
    onCourt: null;
} | {
    ready: null;
}): MatchStatus {
    return "bye" in value ? MatchStatus.bye : "delayed" in value ? MatchStatus.delayed : "completed" in value ? MatchStatus.completed : "notReady" in value ? MatchStatus.notReady : "onCourt" in value ? MatchStatus.onCourt : "ready" in value ? MatchStatus.ready : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerOnCourt: null;
} | {
    notReady: null;
} | {
    categoryClash: null;
} | {
    backToBack: null;
} | {
    timeRisk: null;
} | {
    restNeeded: null;
}): ConflictType {
    return "playerOnCourt" in value ? ConflictType.playerOnCourt : "notReady" in value ? ConflictType.notReady : "categoryClash" in value ? ConflictType.categoryClash : "backToBack" in value ? ConflictType.backToBack : "timeRisk" in value ? ConflictType.timeRisk : "restNeeded" in value ? ConflictType.restNeeded : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CourtFlowCourtView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CourtFlowCourtView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CourtFlowCourtView_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    panicMode: null;
} | {
    completed: null;
} | {
    setup: null;
} | {
    inProgress: null;
}): Variant_panicMode_completed_setup_inProgress {
    return "panicMode" in value ? Variant_panicMode_completed_setup_inProgress.panicMode : "completed" in value ? Variant_panicMode_completed_setup_inProgress.completed : "setup" in value ? Variant_panicMode_completed_setup_inProgress.setup : "inProgress" in value ? Variant_panicMode_completed_setup_inProgress.inProgress : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    waitedTooLong: null;
} | {
    multiCategoryRisk: null;
} | {
    backToBackRisk: null;
}): WaitingWarningType {
    return "waitedTooLong" in value ? WaitingWarningType.waitedTooLong : "multiCategoryRisk" in value ? WaitingWarningType.multiCategoryRisk : "backToBackRisk" in value ? WaitingWarningType.backToBackRisk : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    onTrack: null;
} | {
    urgent: null;
}): CategoryStatus {
    return "delayed" in value ? CategoryStatus.delayed : "onTrack" in value ? CategoryStatus.onTrack : "urgent" in value ? CategoryStatus.urgent : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    resting: null;
} | {
    playing: null;
} | {
    waiting: null;
}): PlayerStatus {
    return "completed" in value ? PlayerStatus.completed : "resting" in value ? PlayerStatus.resting : "playing" in value ? PlayerStatus.playing : "waiting" in value ? PlayerStatus.waiting : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConflictType>): Array<ConflictType> {
    return value.map((x)=>from_candid_ConflictType_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueueEntry>): Array<QueueEntry> {
    return value.map((x)=>from_candid_QueueEntry_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourtFlowCourtView>): Array<CourtFlowCourtView> {
    return value.map((x)=>from_candid_CourtFlowCourtView_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WaitingWarning>): Array<WaitingWarning> {
    return value.map((x)=>from_candid_WaitingWarning_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryView>): Array<CategoryView> {
    return value.map((x)=>from_candid_CategoryView_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchView>): Array<MatchView> {
    return value.map((x)=>from_candid_MatchView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerView>): Array<PlayerView> {
    return value.map((x)=>from_candid_PlayerView_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
